language: rust

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      rust: nightly
      script: cargo doc --lib --no-deps
  allow_failures:
    - os: linux
      rust: nightly

branches:
  except:
  - staging.tmp

before_install:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then rustup default stable-msvc; fi

script:
  - cargo check
  - cargo test --no-run
